### ISSUE TITLE
Malware detected in linux file

### ISSUE THREAD

**Issue by yanfrimmel** [floooh/sokol-tools-bin#9]
virustotal scan detected `Gen:NN.Mirai.36812`.

https://www.virustotal.com/gui/file/bf621f9679b53268fb3af6615e469c3c24f92e4896f4e90325736271aa8fd762/detection

**Comment by floooh** [comment]
Most likely a false positive since the binaries are built on github CI where it's unlikely that an infection can happen. You can compile the binaries yourself though.

**Comment by floooh** [comment]
Did a quick bisect, this is the first 'bad commit' (from 12-Feb-2024):

5b8d524b7faef9d479a48549b3f83511c83e92f0

...the matching sokol-tools commit is this (hardly anything suspicious):

https://github.com/floooh/sokol-tools/commit/6362c8fa26013f6113b6689a40f8b19774afac46

But yeah, since only one of about 70 virus scanners detects anything I would highly suspect that it is a false positive.

One thing I'll do though is logging the executable MD5s during the build process, that way we can check if the executables were tampered with either after the link step, or on the user's machine.

**Comment by floooh** [comment]
For reference, this is the build process for the Linux build (in an Alpine docker image):

https://github.com/floooh/sokol-tools/blob/master/Dockerfile
